name: first_project_1140
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  circular_countdown_timer: ^0.2.3

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  go_router: ^14.2.0
  table_calendar: ^3.1.3
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.9.0

flutter:
  uses-material-design: true

